stages:
  - publish

jobPublishDocker:
  stage: publish
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?-ns-devops-synator/'
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/xtribe/web/infrastructure/images/synator:latest .
    - docker push registry.gitlab.com/xtribe/web/infrastructure/images/synator:latest
