stages:
  - test
  - version
  - publish

include:
  - project: 'Xtribe/Web/infrastructure/gcp-deploy'
    ref: develop_app_version
    file:
      - 'deploy/.gitlab-ci.upstream_infrastructure.yml'

jobSast:
  stage: test
  image: returntocorp/semgrep-agent:v1
  rules:
    - if: '$CI_COMMIT_TAG =~ /^publish-(major|minor|patch)$/'
  script: semgrep-agent
  variables:
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets
