stages:
  - test
  - version
  - publish

include:
  - project: 'Xtribe/Web/infrastructure/gcp-deploy'
    ref: develop_app_version
    file:
      - 'deploy/.gitlab-ci.upstream_infrastructure.yml'

jobSast:
  stage: test
  image: returntocorp/semgrep-agent:v1
  rules:
    - if: '$CI_COMMIT_TAG =~ /^publish-(major|minor|patch)$/'
  script: semgrep-agent
  variables:
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets


jobSastHotfix:
  stage: test
  image: returntocorp/semgrep-agent:v1
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /hotfix/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script: semgrep-agent
  when: manual
  allow_failure: false
  variables:
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets


jobTest:
  stage: test
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  rules:
    - if: '$CI_COMMIT_TAG =~ /^publish-test$/'
  script:
    - TAG_VERSION=0.0.1
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - |
      if [ $(git tag | grep -w '$TAG_VERSION$' | wc -l) -gt 0 ]; then
        echo "test"
        git push --delete origin $TAG_VERSION
        git tag -d $TAG_VERSION
      fi
    - git tag $TAG_VERSION
    - git push origin $TAG_VERSION
    - |
      if [ ! -z $UPSTREAM_CI_COMMIT_TAG ]; then
        git push --delete origin $UPSTREAM_CI_COMMIT_TAG
      fi
