stages:
  - test
  - publish

include:
  - project: 'Xtribe/Web/infrastructure/gcp-deploy'
    ref: develop_app_version
    file:
      - 'deploy/.gitlab-ci.infrascanning.yml'

jobSast:
  stage: test
  image: returntocorp/semgrep-agent:v1
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?-publish/'
  script: semgrep-agent
  variables:
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets

jobTest:
  stage: test
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?-test/'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker image ls
