name: 'Git Repo Sync'
description: 'Git Repo Sync enables you to synchronize code to other code management platforms, such as GitLab, Gitee, etc.'

branding:
  icon: gitlab
  color: yellow

inputs:
  target-url:
    description: 'Target Repo URL'
    required: true
  target-username:
    description: 'Target Repo Username'
    required: true
  target-token:
    description: 'Target Token'
    required: true
  target-branch:
    descirption: 'Target Branch'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TARGET_URL: ${{ inputs.target-url }}
        INPUT_TARGET_USERNAME: ${{ inputs.target-username }}
        INPUT_TARGET_TOKEN: ${{ inputs.target-token }}
        INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
