name: GitlabSync

on:
  - push

jobs:
  sync:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - run: |
        echo Commit MSG = ${{ env.commitmsg }}
