name: GitlabSync

on:
  - push

jobs:
  sync:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - run: |
        COMMIT_MESSAGE=${{ env.commitmsg }}
        BRANCH_TMP=$(echo ${COMMIT_MESSAGE// /_})
        BRANCH_NAME=$(echo $BRANCH_TMP | tr '[:upper:]' '[:lower:]')
        echo $BRANCH_NAME
