name: GitlabSync

on:
  - push

jobs:
  sync:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - run: |
        COMMIT_MESSAGE=echo ${{ env.commitmsg }}
        echo $COMMIT_MESSAGE
        BRANCH_TMP=$(echo ${COMMIT_MESSAGE// /_})
        echo $BRANCH_TMP
        BRANCH_NAME=$(echo $BRANCH_TMP | tr '[:upper:]' '[:lower:]')
        echo $BRANCH_NAME
