name: GitlabSync

on:
  push:
    branches:
      - main

jobs:
  sync:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        COMMIT_MESSAGE=$(echo ${{ env.commitmsg }})
        PULL_REQUEST_NUMBER=22
        BRANCH_NAME="pull_requst_"$PULL_REQUEST_NUMBER
        echo $BRANCH_NAME
        INPUT_TARGET_URL=${{ secrets.TARGET_URL }}
        git remote add target https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@${INPUT_TARGET_URL#https://}
