name: GitlabSync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        INPUT_TARGET_URL=${{ secrets.TARGET_URL }}
        git remote add target https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@${INPUT_TARGET_URL#https://}
        git branch github_pull_request
        git switch github_pull_request
        git push -u target github_pull_request
        MESSAGE=Open new Merge Request: github_pull_request to develop.
        JSON=$(jq -n --arg message "$JSON_MESSAGE" '{message:$MESSAGE,subject:"Open Merge Request From GitHub"}' )
        curl --location --request POST "https://xtribeapp-1279.appspot.com/api/internal/reports/scanner" \
          --header "api-key:RWOI4CQ4A" \
          --header 'Content-Type:application/json' \
          --data-raw "${JSON}"
