name: GitlabSync

on:
  - push

jobs:
  sync:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - run: |
        COMMIT_MESSAGE=$(echo ${{ env.commitmsg }})
        BRANCH_TMP=$(echo ${COMMIT_MESSAGE// /_})
        BRANCH_NAME=$(echo $BRANCH_TMP | tr '[:upper:]' '[:lower:]')
        INPUT_TARGET_URL=${{ secrets.TARGET_URL }}
        git remote add target https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@${INPUT_TARGET_URL#https://}
        git branch $BRANCH_NAME
        git switch $BRANCH_NAME
