name: GitlabSync

on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        INPUT_TARGET_URL=${{ secrets.TARGET_URL }}
        git remote add target https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@${INPUT_TARGET_URL#https://}
        git checkout -b github_pull_request_${GITHUB_RUN_ID}
        git push -u target github_pull_request_${GITHUB_RUN_ID} 
        echo ${{ secrets.TARGET_TOKEN }}
        PROJECT_API=https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT }}/merge_requests
        RESPONSE=$(curl --request POST --header "PRIVATE-TOKEN: ${{ secrets.TARGET_TOKEN }}" --header 'Content-Type: application/json' --data '{"source_branch":"github_pull_request_${GITHUB_RUN_ID}","target_branch":"develop", "title":"Merge Request from GitHub"}' "${PROJECT_API}")
        echo $RESPONSE
        
       
